### ISSUE TITLE
More project types

### ISSUE THREAD

**Issue by filips123** [jarodburchill/ProjectAutomation#1]
Add more project types. This should include:

* skeleton projects for various languages (Python, PHP, Node.js...)
* skeleton projects for specific frameworks (React, Django, Flask, Laravel, Symfony, Slim...)
* other pre-built projects

And also allow users to add their own projects after installation of this program.

**Comment by jarodburchill** [comment]
Thank you for the feedback! I am definitely looking into adding more project types. Also, feel free to fork and submit a pull request for these additional options!

**Comment by jarodburchill** [comment]
We need to come up with a list and break this up into smaller issues

**Comment by jarodburchill** [comment]
Closing and creating smaller issues for new project types.
