### ISSUE TITLE
Python syntax issues from PR #7

### ISSUE THREAD

**Issue by jarodburchill** [jarodburchill/ProjectAutomation#10]
Issues with the if elif else statement

**Comment by Rexogamer** [comment]
Care to elaborate

**Comment by jarodburchill** [comment]
You were missing a bunch of parenthesis and colons in your if elif else statement

**Comment by Rexogamer** [comment]
Ahhh

**Comment by jarodburchill** [comment]
It's my bad I should've cloned and double checked before merging

**Comment by Rexogamer** [comment]
Either way #8 fixes this as it completely redoes editor picking

**Comment by jarodburchill** [comment]
Yeah once I merge #8 it'll close this
