### ISSUE TITLE
Add Atom support

### ISSUE THREAD

**Issue by Rexogamer** [jarodburchill/ProjectAutomation#5]
Add support for Github’s Atom editor.

**Comment by jarodburchill** [comment]
Is there a specific terminal command to open Atom? For example with VS Code you just type `code .`  
  
Thanks for your input, please feel free to submit a pull request if you want to contribute!

**Comment by Rexogamer** [comment]
I found [this](https://stackoverflow.com/questions/22390709/how-to-open-atom-editor-from-command-line-in-os-x) for Mac, I think it’s similar on Windows.

**Comment by Rexogamer** [comment]
You might have to run `Install Shell Commands` beforehand.

**Comment by jarodburchill** [comment]
Will definitely look into adding more text editor support like atom! Thank you for the input. If you want to give it a shot you can fork the repo and make some changes. If the changes work out, you can send a pull request and I'll merge it into the master branch! If you're not looking to contribute, that's okay too. I can work on implementing more text editors on my own. Have a good one!
