### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by jarodburchill** [jarodburchill/ProjectAutomation#53]
Add Vue.js support

**Comment by Rexogamer** [comment]
https://vuejsdevelopers.com/2018/04/23/vue-boilerplate-template-scaffold/ might have some candidates

**Comment by jarodburchill** [comment]
We can just use the Vue CLI

**Comment by Rexogamer** [comment]
Slight issue: the Vue CLI has some option menus when you use vue create.

**Comment by jarodburchill** [comment]
So does node.js and we use that CLI

**Comment by Rexogamer** [comment]
These are mandatory it seems

**Comment by Rexogamer** [comment]
and you don’t type in your answers it seems

**Comment by jarodburchill** [comment]
Trust me, it'll work.
