### ISSUE TITLE
Add option to make a README before opening editor

### ISSUE THREAD

**Issue by Rexogamer** [jarodburchill/ProjectAutomation#6]

**Comment by jarodburchill** [comment]
What do you mean? Instead of the README that comes with the create-react-app?

**Comment by Rexogamer** [comment]
I didn’t know CRA provided that. I guess I was thinking that you would input a custom README (the script would give a field for you to enter the content for it)? Although using CRA might not work when it comes to other languages (eg Node).

**Comment by jarodburchill** [comment]
I think editing the README in a text editor would be better than writing it in the console beforehand. README files can change quite a bit project to project. Thank you for your input :)

**Comment by Rexogamer** [comment]
Fair enough.
